# Generated by Django 3.0.6 on 2020-08-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasoseol',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jasoseol',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
