# Generated by Django 3.0.8 on 2020-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200802_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jasoseol',
            name='update_at',
        ),
        migrations.AddField(
            model_name='jasoseol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
