# Generated by Django 3.0.8 on 2020-08-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200802_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jasoseol',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jasoseol',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
